/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import Vaccination.Doctor.Doctor;
import Vaccination.Doctor.OrderArray;
import Vaccination.Configuration.EcoSystem;
import Vaccination.Enterprise.Enterprise;
import Vaccination.Network.Network;
import Vaccination.Organization.DoctorOrg;
import Vaccination.UserAccount.UserAccount;
import Vaccination.WorkQueue.DoctorWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author prakruthisomashekar
 */
public class DoctorMainAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DoctorOrg organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Doctor doctor;
    private OrderArray list;
    private DoctorWorkRequest docreq;
    private Network network;
    private EcoSystem system;
    private static Logger log = Logger.getLogger(DoctorMainAreaJPanel.class);
    private static final String CLASS_NAME = DoctorMainAreaJPanel.class.getName();

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DoctorMainAreaJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrg organization, Enterprise enterprise, EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        network();

    }

    public void network() {
        network.getName();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrecriptionBtn = new javax.swing.JButton();
        labTestBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 235, 204));
        setPreferredSize(new java.awt.Dimension(2000, 1200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PrecriptionBtn.setBackground(new java.awt.Color(0, 0, 0));
        PrecriptionBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        PrecriptionBtn.setForeground(new java.awt.Color(255, 255, 255));
        PrecriptionBtn.setText("ADD PRESCRIPTIONS");
        PrecriptionBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PrecriptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecriptionBtnActionPerformed(evt);
            }
        });
        add(PrecriptionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 221, 49));

        labTestBtn.setBackground(new java.awt.Color(0, 0, 0));
        labTestBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        labTestBtn.setForeground(new java.awt.Color(255, 255, 255));
        labTestBtn.setText("COVID-19 VARIANT TEST & CLINICAL TRIALS");
        labTestBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        labTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labTestBtnActionPerformed(evt);
            }
        });
        add(labTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 430, 360, 56));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/prescription-icon.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 260, 250));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/test.jpeg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 240, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void PrecriptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecriptionBtnActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        log.debug("inside doctor role");
        userProcessContainer.add("PrescriptionJPanel", new userinterface.Doctor.AddPrescriptionMedicineJPanel(userProcessContainer, list, userAccount, enterprise, organization, system, network));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_PrecriptionBtnActionPerformed

    private void labTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labTestBtnActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        log.debug("inside doctor's lab request");
        userProcessContainer.add("TestJPanel", new userinterface.Doctor.DoctorRequestJpanel(userProcessContainer, userAccount, organization, enterprise, system, network));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_labTestBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PrecriptionBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton labTestBtn;
    // End of variables declaration//GEN-END:variables
}
