/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import Vaccination.Doctor.Patient;
import Vaccination.Configuration.EcoSystem;
import Vaccination.Enterprise.Enterprise;
import Vaccination.Connection.Connection;
import Vaccination.Organization.Clinic;
import Vaccination.Organization.DoctorOrg;
import Vaccination.Organization.Laboratory;
import Vaccination.Organization.Organization;
import Vaccination.UserAccount.UserAcc;
import Vaccination.WorkQueue.ClinicalTrialWorkRequest;
import Vaccination.WorkQueue.LabTestWorkRequest;
import Vaccination.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author prakruthisomashekar
 */

public class DocWorkRequestJpanel extends javax.swing.JPanel {

    /**
     * Creates new form DocWorkRequestJpanel
     */
    private JPanel userProcessContainer;
    private UserAcc account;
    private DoctorOrg docOrganization;
    private Enterprise enterprise;

    private Connection network;
    private EcoSystem system;
    private Enterprise.EnterpriseType enterpriseType;
    private static Logger log = Logger.getLogger(DocWorkRequestJpanel.class);
    private static final String CLASS_NAME = DocWorkRequestJpanel.class.getName();

    public DocWorkRequestJpanel(JPanel userProcessContainer, UserAcc account, DoctorOrg organization, Enterprise enterprise, EcoSystem system, Connection network) {
        initComponents();
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.docOrganization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        populateRequestTable();
        populateClinicalRequestTable();
     

    }

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) doctorRequestTbl.getModel();

        model.setRowCount(0);
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {
            if (request instanceof LabTestWorkRequest) {
                Object[] row = new Object[7];
                row[0] = ((LabTestWorkRequest) request);
                row[1] = ((LabTestWorkRequest) request).getPatient().getAge();
                row[2] = ((LabTestWorkRequest) request).getPatient().getSex();
                row[3] = request.getMessage();

                row[4] = request.getReceiver();
                row[5] = request.getStatus();
                String result = ((LabTestWorkRequest) request).getPatient().getVariantHistory().getVariantHistory().getVariantName();
                if (request.getReceiver() == null || request.getReceiver().equals("Processing")) {
                    row[6] = null;
                } else {
                    row[6] = result;
                }

                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultsLbl = new javax.swing.JLabel();
        refreshbtn = new javax.swing.JButton();
        requestTestBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorRequestTbl = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        sexLbl = new javax.swing.JLabel();
        testTxtField = new javax.swing.JTextField();
        diagnosisLbl = new javax.swing.JLabel();
        ageLbl = new javax.swing.JLabel();
        ageTxtField = new javax.swing.JTextField();
        viewResultsbtn = new javax.swing.JButton();
        sexcomboBox = new javax.swing.JComboBox<>();
        btnClinicalTrial = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        doctorClinicRequestTbl = new javax.swing.JTable();
        resultsLbl1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        patientEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 235, 204));
        setForeground(new java.awt.Color(0, 0, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultsLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        resultsLbl.setForeground(new java.awt.Color(0, 0, 153));
        resultsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultsLbl.setText("LAB TEST RESULTS");
        add(resultsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 615, 40));

        refreshbtn.setBackground(new java.awt.Color(0, 0, 0));
        refreshbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        refreshbtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshbtn.setText("REFRESH");
        refreshbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });
        add(refreshbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 80, 30));

        requestTestBtn.setBackground(new java.awt.Color(0, 0, 0));
        requestTestBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        requestTestBtn.setForeground(new java.awt.Color(255, 255, 255));
        requestTestBtn.setText("REQUEST TEST");
        requestTestBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        requestTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestBtnActionPerformed(evt);
            }
        });
        add(requestTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 110, 30));

        doctorRequestTbl.setBackground(new java.awt.Color(102, 102, 102));
        doctorRequestTbl.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        doctorRequestTbl.setForeground(new java.awt.Color(255, 255, 255));
        doctorRequestTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Age", "Sex", "Message", "Receiver", "Status", "Variant"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doctorRequestTbl.setRowHeight(25);
        jScrollPane1.setViewportView(doctorRequestTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 615, 170));

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("BACK");
        backJButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 69, 30));

        nameLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(0, 0, 153));
        nameLbl.setText("NAME:");
        add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));
        add(nameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 162, -1));

        sexLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        sexLbl.setForeground(new java.awt.Color(0, 0, 153));
        sexLbl.setText("GENDER:");
        add(sexLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));
        add(testTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 168, -1));

        diagnosisLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        diagnosisLbl.setForeground(new java.awt.Color(0, 0, 153));
        diagnosisLbl.setText("TEST NAME:");
        add(diagnosisLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        ageLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        ageLbl.setForeground(new java.awt.Color(0, 0, 153));
        ageLbl.setText("AGE:");
        add(ageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));
        add(ageTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 162, -1));

        viewResultsbtn.setBackground(new java.awt.Color(0, 0, 0));
        viewResultsbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewResultsbtn.setForeground(new java.awt.Color(255, 255, 255));
        viewResultsbtn.setText("VIEW RESULTS");
        viewResultsbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        viewResultsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewResultsbtnActionPerformed(evt);
            }
        });
        add(viewResultsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 120, 30));

        sexcomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "MALE", "FEMALE" }));
        sexcomboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexcomboBoxActionPerformed(evt);
            }
        });
        add(sexcomboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        btnClinicalTrial.setBackground(new java.awt.Color(0, 0, 0));
        btnClinicalTrial.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnClinicalTrial.setForeground(new java.awt.Color(255, 255, 255));
        btnClinicalTrial.setText("REQUST ADVANCED TEST");
        btnClinicalTrial.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnClinicalTrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClinicalTrialActionPerformed(evt);
            }
        });
        add(btnClinicalTrial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 180, 30));

        doctorClinicRequestTbl.setBackground(new java.awt.Color(102, 102, 102));
        doctorClinicRequestTbl.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        doctorClinicRequestTbl.setForeground(new java.awt.Color(255, 255, 255));
        doctorClinicRequestTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Age", "Sex", "Message", "Receiver", "Status", "Sample"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doctorClinicRequestTbl.setRowHeight(25);
        jScrollPane2.setViewportView(doctorClinicRequestTbl);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 615, 170));

        resultsLbl1.setBackground(new java.awt.Color(0, 0, 0));
        resultsLbl1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        resultsLbl1.setForeground(new java.awt.Color(0, 0, 153));
        resultsLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultsLbl1.setText("ADVANCED LAB TEST RESULTS");
        add(resultsLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 615, 40));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("E-MAIL:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));
        add(patientEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 161, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("REQUEST FOR ADVANCED LAB TEST AND LAB TEST ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed

        populateRequestTable();

    }//GEN-LAST:event_refreshbtnActionPerformed

    private void requestTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestBtnActionPerformed

        String message = testTxtField.getText().trim();
        String patientName = nameTxtField.getText();
        String sex = sexcomboBox.getSelectedItem().toString();
        String email = patientEmail.getText();
        boolean flag = true;
        if (sexcomboBox.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(null, "Please select the sex");
            return;
        }
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Write the test need to be performed");
            return;
        }
        int age;
        try {
            age = Integer.parseInt(ageTxtField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Age must be integer!");
            return;
        }
                String regex = "^(.+)@(.+)$";
        Pattern pattern = Pattern.compile(regex);
        if(!patientEmail.getText().isEmpty()){
        Matcher matcher = pattern.matcher(patientEmail.getText());
            if(matcher.matches()){
            }else{
                JOptionPane.showMessageDialog(null, "Email is not in proper format");
                flag = false;
                return;
            }
        }else{
            JOptionPane.showMessageDialog(null, "Email cannot be empty");
            flag = false;
            return;
        }
        if(flag = true){
        LabTestWorkRequest request = new LabTestWorkRequest();
        request.setMessage(message);
        request.setEndUser(account);
        request.setStatus("Sent");
        request.setPatientName(patientName);
        Patient patient = new Patient();
        patient.setPName(patientName);
        patient.setAge(age);
        patient.setTest(message);
        patient.setSex(sex);
        patient.setMail(email);
        request.setPatient(patient);

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof Laboratory) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWq().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
            log.debug("Sent request to Lab");
        }
        populateRequestTable();
        JOptionPane.showMessageDialog(null, "Test has been requested successfully");
        nameTxtField.setText("");
        ageTxtField.setText("");
        sexcomboBox.setSelectedIndex(0);
        testTxtField.setText("");
         patientEmail.setText("");
        }
    }//GEN-LAST:event_requestTestBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorMainAreaJPanel dwjp = (DoctorMainAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void viewResultsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewResultsbtnActionPerformed
        int selectedRow = doctorRequestTbl.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select a row to view results");
            return;
        }

        LabTestWorkRequest request = (LabTestWorkRequest) doctorRequestTbl.getValueAt(selectedRow, 0);
        System.out.println(doctorRequestTbl.getValueAt(selectedRow, 5));
        System.out.println(!(doctorRequestTbl.getValueAt(selectedRow, 5).toString().toLowerCase().equalsIgnoreCase("completed")));

        if (doctorRequestTbl.getValueAt(selectedRow, 6) == null) {
            JOptionPane.showMessageDialog(null, "Results need to be generated by lab assistant");
            return;
        }
        int flag = 0;
        if ((doctorRequestTbl.getValueAt(selectedRow, 5).toString().equalsIgnoreCase("completed"))) {

            flag++;

        }

        if (flag == 0) {
            JOptionPane.showMessageDialog(null, "Lab results are  not yet returned");
            return;
        }

        DoctorLabTestResultsJpanel processWorkRequestJPanel = new DoctorLabTestResultsJpanel(userProcessContainer, request);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        log.debug("adding request to lab assistant");
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewResultsbtnActionPerformed

    private void sexcomboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexcomboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexcomboBoxActionPerformed

    private void btnClinicalTrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClinicalTrialActionPerformed
        // TODO add your handling code here:

        String message = testTxtField.getText().trim();
        String patientName = nameTxtField.getText();
        String sex = sexcomboBox.getSelectedItem().toString();
        String email=patientEmail.getText();
        boolean flag = true;
        if (sexcomboBox.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(null, "Please select the sex");
            return;
        }
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Write the test need to be performed");
            return;
        }
        int age;
        try {
            age = Integer.parseInt(ageTxtField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Age must be integer!");
            return;
        }

                String regex = "^(.+)@(.+)$";
        Pattern pattern = Pattern.compile(regex);
        if(!patientEmail.getText().isEmpty()){
        Matcher matcher = pattern.matcher(patientEmail.getText());
            if(matcher.matches()){
            }else{
                JOptionPane.showMessageDialog(null, "Email is not in proper format");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Email cannot be empty");
        }
        if(flag = true){
        ClinicalTrialWorkRequest request = new ClinicalTrialWorkRequest();
        request.setMessage(message);
        request.setEndUser(account);
        request.setStatus("Sent");
        request.setPatientName(patientName);
        Patient patient = new Patient();
        patient.setPName(patientName);
        patient.setAge(age);
        patient.setTest(message);
        patient.setSex(sex);
        patient.setMail(email);
        request.setPatient(patient);

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof Clinic) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWq().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
            log.debug("Sent request to Clinic");
        }
        populateClinicalRequestTable();
        JOptionPane.showMessageDialog(null, "Test has been requested successfully");
        nameTxtField.setText("");
        ageTxtField.setText("");
        sexcomboBox.setSelectedIndex(0);
        testTxtField.setText("");
        patientEmail.setText("");
        }
    }//GEN-LAST:event_btnClinicalTrialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField ageTxtField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnClinicalTrial;
    private javax.swing.JLabel diagnosisLbl;
    private javax.swing.JTable doctorClinicRequestTbl;
    private javax.swing.JTable doctorRequestTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JTextField patientEmail;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JButton requestTestBtn;
    private javax.swing.JLabel resultsLbl;
    private javax.swing.JLabel resultsLbl1;
    private javax.swing.JLabel sexLbl;
    private javax.swing.JComboBox<String> sexcomboBox;
    private javax.swing.JTextField testTxtField;
    private javax.swing.JButton viewResultsbtn;
    // End of variables declaration//GEN-END:variables
    public void populateClinicalRequestTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) doctorClinicRequestTbl.getModel();

            model.setRowCount(0);
            for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {
                if (request instanceof ClinicalTrialWorkRequest) {
                    Object[] row = new Object[7];
                    row[0] = ((ClinicalTrialWorkRequest) request);
                    row[1] = ((ClinicalTrialWorkRequest) request).getPatient().getAge();
                    row[2] = ((ClinicalTrialWorkRequest) request).getPatient().getSex();
                    row[3] = request.getMessage();

                    row[4] = request.getReceiver();
                    row[5] = request.getStatus();
                    String result = ((ClinicalTrialWorkRequest) request).getPatient().getVariantHistory().getVariantHistory().getVariantName();
                    if (request.getReceiver() == null || request.getReceiver().equals("Processing")) {
                        row[6] = null;
                    } else {
                        row[6] = result;
                    }

                    model.addRow(row);
                }
            }
        } catch (Exception e) {
            System.out.println("doctor request panel table yet to populate");
        }
    }

}
