/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface.VaccineRole;

import Waypoint.MyWaypoint;
import Waypoint.WaypointRender;
import java.util.HashSet;
import java.util.Set;
import javax.swing.event.MouseInputListener;
import org.jxmapviewer.OSMTileFactoryInfo;
import org.jxmapviewer.VirtualEarthTileFactoryInfo;
import org.jxmapviewer.input.PanMouseInputListener;
import org.jxmapviewer.input.ZoomMouseWheelListenerCenter;
import org.jxmapviewer.viewer.DefaultTileFactory;
import org.jxmapviewer.viewer.GeoPosition;
import org.jxmapviewer.viewer.TileFactoryInfo;
import org.jxmapviewer.viewer.WaypointPainter;

/**
 *
 * @author tiyashasen
 */
public class GoogleMap extends javax.swing.JFrame {

    /**
     * Creates new form GoogleMap
     */
    
        private final Set<MyWaypoint> waypoints=new HashSet<>();
    public GoogleMap() {
        initComponents();
        init();
    }

    
    public void init(){
            TileFactoryInfo info = new OSMTileFactoryInfo();
            DefaultTileFactory tileFactory=new DefaultTileFactory(info);
            jXMapViewer.setTileFactory(tileFactory);
            GeoPosition geo=new GeoPosition(42.34344714715224, -71.08962464658437);
            jXMapViewer.setAddressLocation(geo);
            jXMapViewer.setZoom(12);
            
            //Create event mouse move
            MouseInputListener mm=new PanMouseInputListener(jXMapViewer);
            jXMapViewer.addMouseListener(mm);
            jXMapViewer.addMouseMotionListener(mm);
            jXMapViewer.addMouseWheelListener(new ZoomMouseWheelListenerCenter(jXMapViewer));
    }

    private void initWaypoint(){
        WaypointPainter<MyWaypoint> wp=new WaypointRender();
        
        wp.setWaypoints(waypoints);
        jXMapViewer.setOverlayPainter(wp);
        for(MyWaypoint d: waypoints){
            jXMapViewer.add(d.getButton());
        }
        
    }
    
    private void addWaypoint(MyWaypoint wayPoint){
        for(MyWaypoint d : waypoints){
            jXMapViewer.remove(d.getButton());
            
        }
        waypoints.add(wayPoint);
        initWaypoint();
        
    }
        
    
    private void clearWaypoint()
    {
        for(MyWaypoint d: waypoints){
            jXMapViewer.remove(d.getButton());      
        }
        waypoints.clear();
        initWaypoint();
    }
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXMapViewer = new org.jxmapviewer.JXMapViewer();
        comboMapType = new javax.swing.JComboBox<>();
        cmdAdd = new javax.swing.JButton();
        cmdClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXMapViewer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboMapType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Open Stree", "Virtual Earth", "Hybrid", "Satellite" }));
        comboMapType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMapTypeActionPerformed(evt);
            }
        });
        jXMapViewer.add(comboMapType, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 6, 127, 31));

        cmdAdd.setText("Add Waypoint");
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });
        jXMapViewer.add(cmdAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        cmdClear.setText("Clear Waypoint");
        cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearActionPerformed(evt);
            }
        });
        jXMapViewer.add(cmdClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 10, -1, -1));

        getContentPane().add(jXMapViewer, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 710, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboMapTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMapTypeActionPerformed
        TileFactoryInfo info;
        int index=comboMapType.getSelectedIndex();
        if(index==0){
            info = new OSMTileFactoryInfo();
        }
        else if(index==1){
            info = new VirtualEarthTileFactoryInfo(VirtualEarthTileFactoryInfo.MAP);
        }
        else if(index==2){
            info = new VirtualEarthTileFactoryInfo(VirtualEarthTileFactoryInfo.HYBRID);
        }
        else{
             info = new VirtualEarthTileFactoryInfo(VirtualEarthTileFactoryInfo.SATELLITE);
        }
        DefaultTileFactory tileFactory= new DefaultTileFactory(info);
        jXMapViewer.setTileFactory(tileFactory);
             
    }//GEN-LAST:event_comboMapTypeActionPerformed

    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
        // TODO add your handling code here:
        addWaypoint( new MyWaypoint("Test 001", new GeoPosition(42.343, -71.0896)));
       addWaypoint( new MyWaypoint("Test 002", new GeoPosition(42.343, -71.089)));
    }//GEN-LAST:event_cmdAddActionPerformed

    private void cmdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearActionPerformed
        // TODO add your handling code here:
        clearWaypoint();
    }//GEN-LAST:event_cmdClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GoogleMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GoogleMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GoogleMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoogleMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GoogleMap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdClear;
    private javax.swing.JComboBox<String> comboMapType;
    private org.jxmapviewer.JXMapViewer jXMapViewer;
    // End of variables declaration//GEN-END:variables
}
