/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VaccineRole;

import Vaccination.WorkQueue.VaccineWorkRequest;
import Vaccination.WorkQueue.MedicineWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author tiyashasen
 */
public class VaccineProcessRequestJpanel extends javax.swing.JPanel {

    /**
     * Creates new form VaccineProcessRequestJpanel
     */
    JPanel userProcessContainer;
    VaccineWorkRequest request;
    private static Logger log = Logger.getLogger(VaccineProcessRequestJpanel.class);
    private static final String CLASS_NAME = VaccineProcessRequestJpanel.class.getName();

    public VaccineProcessRequestJpanel(JPanel userprocessContainer, VaccineWorkRequest request) {
        initComponents();
        this.userProcessContainer = userprocessContainer;
        this.request = request;
        dateTxt.setMinSelectableDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        processlbl = new javax.swing.JLabel();
        datedeliveryBtn = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtext = new javax.swing.JTextField();
        dateTxt = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(233, 235, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        processlbl.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        processlbl.setForeground(new java.awt.Color(0, 0, 204));
        processlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        processlbl.setText(" MEDICINE SUPPLIER REQUEST ");
        add(processlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 550, 40));

        datedeliveryBtn.setBackground(new java.awt.Color(255, 255, 255));
        datedeliveryBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        datedeliveryBtn.setForeground(new java.awt.Color(51, 51, 0));
        datedeliveryBtn.setText("DATE OF DELIVERY : ");
        add(datedeliveryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 150, 30));

        backBtn.setBackground(new java.awt.Color(102, 102, 255));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("BACK");
        backBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 94, 39));

        updateBtn.setBackground(new java.awt.Color(102, 102, 255));
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("UPDATE STATUS ");
        updateBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, 148, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/tiyashasen/Desktop/images/delivery-medicines-176785219.jpeg")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 800, 520));

        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 110, 40));
        add(jtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 100, 30));
        add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VaccineWorkArea dwjp = (VaccineWorkArea) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        request.setStatus("Completed");
        try {
            int year = dateTxt.getCalendar().get(Calendar.YEAR);
            int month = dateTxt.getCalendar().get(Calendar.MONTH);
            int day = dateTxt.getCalendar().get(Calendar.DAY_OF_MONTH);
            String result = year + "-" + month + "-" + day;
            ((VaccineWorkRequest) request).setTOD(result);
            jtext.setText(result);
            JOptionPane.showMessageDialog(null, "Request updated successfully!");
            log.debug("request updated successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "please enter the valid date");
            return;
        }
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private com.toedter.calendar.JDateChooser dateTxt;
    private javax.swing.JLabel datedeliveryBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtext;
    private javax.swing.JLabel processlbl;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
