/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MedicineManufactureResearch;

import Vaccination.Enterprise.Enterprise;
import Vaccination.Organization.Medicine;
import Vaccination.UserAccount.UserAcc;
import Vaccination.WorkQueue.VaccineWorkRequest;
import Vaccination.WorkQueue.MedicineWorkRequest;
import Vaccination.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import userinterface.PharmacyRole.PharmacyMainJPanel;

/**
 *
 * @author prakruthisomashekar
 */
public class GetVaccineRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GetVaccineRequestsJPanel
     */
    private JPanel userProcessContainer;
    private UserAcc userAccount;
    private Enterprise enterprise;
    private Medicine medOrganization;
    private static Logger log = Logger.getLogger(GetVaccineRequestsJPanel.class);
    private static final String CLASS_NAME = GetVaccineRequestsJPanel.class.getName();

    public GetVaccineRequestsJPanel(JPanel userProcessContainer, UserAcc userAccount, Enterprise enterprise, Medicine MOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.medOrganization = MOrganization;
        populateTable();
    }

    public void populateTable() {
        try{
        DefaultTableModel model = (DefaultTableModel) drugRequestsTable.getModel();

        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[5];
            row[0] = ((VaccineWorkRequest) request);
            row[1] = ((VaccineWorkRequest) request).getQty();
            row[2] = request.getReceiver();
            String result = ((VaccineWorkRequest) request).getStatus();
            row[3] = result == null ? "Waiting" : result;
            if (((VaccineWorkRequest) request).getTOD() == null) {
                row[4] = "Details yet to be updated by supplier";
            } else {
                row[4] = "Expected delivery time " + ((VaccineWorkRequest) request).getTOD();
            }

            model.addRow(row);
        }
        }
        catch(Exception e){
            System.out.println("view vaccine table is yet to populate");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        drugRequestsTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 235, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        drugRequestsTable.setBackground(new java.awt.Color(102, 102, 102));
        drugRequestsTable.setForeground(new java.awt.Color(255, 255, 255));
        drugRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VACCINE NAME", "REQUIRED QUANTITY", "RECIEVER", "STATUS", "DELIVERY DATE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        drugRequestsTable.setRowHeight(30);
        jScrollPane.setViewportView(drugRequestsTable);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 655, 213));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("BACK");
        backBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 79, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VIEW REQUESTS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 655, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AddVaccineRequestsJPanel dw = (AddVaccineRequestsJPanel) component;
        dw.reorderTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable drugRequestsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
