/*
 * To change this license header, choose License Headers in Project Properties. To change this
 * template file, choose Tools | Templates and open the template in the editor.
 */
package userinterface.Vaccine;

import Vaccination.SampleInventory.SampleCompound;
import Vaccination.Enterprise.Enterprise;
import Vaccination.MedicalInventory.MedicalInventoryList;
import Vaccination.Organization.Vaccine;
import Vaccination.UserAccount.UserAcc;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author tiyashasen
 */
public class GetSampleDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GetSampleDetailsJPanel
     */
    JPanel userProcessContainer;
    private UserAcc userAccount;
    private Enterprise enterprise;
    private MedicalInventoryList mil;
    private Vaccine drugOrg;
    private SampleCompound mi;
    private static Logger log = Logger.getLogger(GetSampleDetailsJPanel.class);
    private static final String CLASS_NAME = GetSampleDetailsJPanel.class.getName();

    public GetSampleDetailsJPanel(JPanel userProcessContainer, UserAcc userAccount,
            Enterprise enterprise, SampleCompound mi) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.drugOrg = drugOrg;
        this.mi = mi;
        serialNumTextField.setText(String.valueOf(mi.getSerialNumber()));
        availQuantityTextField.setText(String.valueOf(mi.getAvailQuantity()));
        chemicalNameTextField.setText(mi.getSampleName());
        try {
            String phone = JOptionPane.showInputDialog(null, "Please enter phone number");
            String opt = JOptionPane.showInputDialog(null, "Please enter the generated OTP.");
            if (opt.equalsIgnoreCase("12697") || opt.equalsIgnoreCase("30897")
                    || opt.equalsIgnoreCase("28596") || opt.equalsIgnoreCase("15067")) {
                serialNumTextField.setEnabled(true);
                chemicalNameTextField.setEnabled(true);
                availQuantityTextField.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "No Update Access.");
                serialNumTextField.setEnabled(false);
                chemicalNameTextField.setEnabled(false);
                availQuantityTextField.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Update Access.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serialNumLabel = new javax.swing.JLabel();
        serialNumTextField = new javax.swing.JTextField();
        drugLabel = new javax.swing.JLabel();
        chemicalNameTextField = new javax.swing.JTextField();
        availLabel = new javax.swing.JLabel();
        availQuantityTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 235, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serialNumLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        serialNumLabel.setText("SERIAL NUMBER:");
        add(serialNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 140, 30));

        serialNumTextField.setEditable(false);
        serialNumTextField.setBackground(new java.awt.Color(102, 102, 102));
        serialNumTextField.setForeground(new java.awt.Color(255, 255, 255));
        serialNumTextField.setBorder(null);
        add(serialNumTextField,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 130, 30));

        drugLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        drugLabel.setText("VACCINE NAME:");
        add(drugLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 120, 30));

        chemicalNameTextField.setEditable(false);
        chemicalNameTextField.setBackground(new java.awt.Color(102, 102, 102));
        chemicalNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        chemicalNameTextField.setBorder(null);
        add(chemicalNameTextField,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 130, 30));

        availLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        availLabel.setText("AVAILABILITY:");
        add(availLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 120, 30));

        availQuantityTextField.setEditable(false);
        availQuantityTextField.setBackground(new java.awt.Color(102, 102, 102));
        availQuantityTextField.setForeground(new java.awt.Color(255, 255, 255));
        availQuantityTextField.setBorder(null);
        availQuantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availQuantityTextFieldActionPerformed(evt);
            }
        });
        add(availQuantityTextField,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 130, 30));

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText(" BACK");
        backButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1,
                new java.awt.Color(255, 255, 255)));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 74, 32));

        saveButton.setBackground(new java.awt.Color(0, 0, 0));
        saveButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("SAVE");
        saveButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1,
                new java.awt.Color(255, 255, 255)));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 70, 40));

        updateButton.setBackground(new java.awt.Color(0, 0, 0));
        updateButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("UPDATE");
        updateButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1,
                new java.awt.Color(255, 255, 255)));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 100, 40));

        jLabel1.setBackground(new java.awt.Color(51, 153, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VACCINE DETAILS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 260, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/employee-3.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 520, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void availQuantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_availQuantityTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_availQuantityTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        GetSampleRequestsJPanel me = (GetSampleRequestsJPanel) component;
        me.reorderTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }// GEN-LAST:event_backButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (chemicalNameTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "chemical name is empty");
            return;
        }
        mi.setSampleName(chemicalNameTextField.getText());

        try {
            int availableQuantity = Integer.parseInt(availQuantityTextField.getText());
            mi.setAvailQuantity(availableQuantity);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Available quantity must be integer");
            return;
        }
        try {
            int serialNumber = Integer.parseInt(serialNumTextField.getText());
            mi.setSerialNumber(serialNumber);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Serial number must be integer");
            return;
        }

        saveButton.setEnabled(false);
        updateButton.setEnabled(true);
        chemicalNameTextField.setEditable(false);
        serialNumTextField.setEditable(false);
        availQuantityTextField.setEditable(false);

        JOptionPane.showMessageDialog(null, "Medicine updated Successfully", "Warning",
                JOptionPane.INFORMATION_MESSAGE);
        log.debug(userAccount + " " + "updated chemical details successfully");
    }// GEN-LAST:event_saveButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateButtonActionPerformed

        chemicalNameTextField.setEditable(true);
        serialNumTextField.setEditable(true);
        availQuantityTextField.setEditable(true);
        updateButton.setEnabled(false);
        saveButton.setEnabled(true);
    }// GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availLabel;
    private javax.swing.JTextField availQuantityTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField chemicalNameTextField;
    private javax.swing.JLabel drugLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel serialNumLabel;
    private javax.swing.JTextField serialNumTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
